/**
 * Generates size.js guard — detects oversized files and heavy exporters.
 * Supports per-extension overrides for multi-language projects.
 */
export function generateSizeGuard(): string {
  return `/**
 * size.js — Guard: Oversized file detection
 * Generated by AICodeSight.
 *
 * Supports per-extension thresholds in guard-config.json:
 *   "size": {
 *     "severity": "warn",
 *     "maxLines": 350,
 *     "maxExports": 5,
 *     "overrides": {
 *       ".cs": { "maxLines": 500, "maxExports": 8 }
 *     }
 *   }
 */
module.exports = {
  name: 'size',

  check(ctx) {
    const config = ctx.config.guards.size || {};
    const overrides = config.overrides || {};

    // Resolve effective thresholds: extension override > global default
    const extOverride = overrides[ctx.ext] || {};
    const maxLines = extOverride.maxLines || config.maxLines || 350;
    const maxExports = extOverride.maxExports || config.maxExports || 5;

    const messages = [];
    const lines = ctx.content.split('\\n').length;

    // Skip index/barrel files for export count
    const path = require('path');
    const baseName = path.basename(ctx.relativePath, ctx.ext);
    const isBarrel = baseName === 'index' || baseName === 'barrel';

    if (lines > maxLines) {
      const severity = lines > maxLines * 3 ? 'warn' : 'info';
      messages.push({
        severity,
        identifier: 'size:lines:' + ctx.relativePath,
        text: 'File has ' + lines + ' lines (limit: ' + maxLines + ')',
        suggestion: 'Consider extracting responsibilities to separate files',
      });
    }

    if (!isBarrel && ctx.fileExports.length > maxExports) {
      messages.push({
        severity: 'warn',
        identifier: 'size:exports:' + ctx.relativePath,
        text: 'File has ' + ctx.fileExports.length + ' exports (limit: ' + maxExports + ')',
        suggestion: 'Split into smaller modules with single responsibility',
      });
    }

    return { passed: messages.length === 0, messages };
  },
};
`;
}
