import { ProjectProfile } from '../types';

export function generateClaudeIgnore(profile: ProjectProfile): string {
  const lines: string[] = [];

  lines.push('# Generated by AICodeSight');
  lines.push('# Files and folders that Claude Code should ignore');
  lines.push('');

  // Common ignores
  lines.push('# Dependencies');
  lines.push('node_modules/');
  lines.push('');

  lines.push('# Build output');
  lines.push('dist/');
  lines.push('build/');
  lines.push('out/');
  lines.push('.next/');
  lines.push('');

  lines.push('# Cache');
  lines.push('.cache/');
  lines.push('.turbo/');
  lines.push('.nuxt/');
  lines.push('');

  lines.push('# Coverage');
  lines.push('coverage/');
  lines.push('');

  lines.push('# Environment');
  lines.push('.env');
  lines.push('.env.local');
  lines.push('.env.*.local');
  lines.push('');

  lines.push('# Lock files');
  lines.push('package-lock.json');
  lines.push('yarn.lock');
  lines.push('pnpm-lock.yaml');
  lines.push('');

  lines.push('# Generated');
  lines.push('*.min.js');
  lines.push('*.min.css');
  lines.push('*.map');
  lines.push('');

  // Framework-specific
  if (profile.frameworks.includes('Next.js')) {
    lines.push('# Next.js');
    lines.push('.next/');
    lines.push('');
  }

  if (profile.frameworks.includes('Prisma')) {
    lines.push('# Prisma');
    lines.push('prisma/migrations/');
    lines.push('');
  }

  // Monorepo
  if (profile.structure === 'monorepo') {
    lines.push('# Monorepo - ignore package builds');
    lines.push('packages/*/dist/');
    lines.push('packages/*/build/');
    lines.push('');
  }

  lines.push('# Binary assets');
  lines.push('*.png');
  lines.push('*.jpg');
  lines.push('*.jpeg');
  lines.push('*.gif');
  lines.push('*.ico');
  lines.push('*.svg');
  lines.push('*.woff');
  lines.push('*.woff2');
  lines.push('*.ttf');
  lines.push('*.eot');
  lines.push('');

  return lines.join('\n');
}
